version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "14:06"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
