version: 2
updates:
  - package-ecosystem: gradle
    directory: "/gradle"
    schedule:
      interval: daily
      time: "13:45"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "14:05"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
